<?php

/**
 * @file
 * Module hooks for the ooh_outskirts module.
 */

/**
 * Implements hook_theme().
 */
function ooh_outskirts_theme($existing, $type, $theme, $path) {
  return [
    'ooh_landing_page' => [
      'variables' => [
        'loops' => [],
      ],
      'template' => 'ooh-landing-page',
    ],
    'ooh_clearance_block' => [
      'variables' => [],
      'template' => 'block--ooh-clearance-block',
    ],
    'ooh_credits_block' => [
      'variables' => [],
      'template' => 'block--ooh-credits-block',
    ],
  ];
}
